name: Create Extension Release Zip

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Extension Files
        run: |
          zip -r sap-public-cloud-helper.zip . -x "*.git*" ".github/*" "index.html"

      - name: Release Zip Asset to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: sap-public-cloud-helper.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
